// Default deck for the values card sort. Edit this list to change the starting cards.
const DEFAULT_CARDS = [
  { id: "autonomy", name: "Autonomy", description: "Deciding how and when I do my own work" },
  { id: "mentorship", name: "Mentorship", description: "Someone actively teaching and guiding me" },
  { id: "fast-pace", name: "Fast pace", description: "Constant motion, quick turnaround, energy" },
  { id: "stability", name: "Stability", description: "Predictable, secure, low-risk path" },
  { id: "creative-freedom", name: "Creative freedom", description: "Room to originate ideas, not just execute" },
  { id: "clear-advancement", name: "Clear advancement", description: "A visible next step and path upward" },
  { id: "working-with-people", name: "Working with people", description: "Collaborating, talking, being around others daily" },
  { id: "solo-focus", name: "Solo focus", description: "Heads-down, independent, minimal interruption" },
  { id: "mission", name: "Mission I believe in", description: "The purpose of the work matters to me" },
  { id: "high-earning", name: "High earning potential", description: "Money and financial upside matter now" },
  { id: "flexibility", name: "Flexibility", description: "Control over hours, location, how work fits life" },
  { id: "constant-learning", name: "Constant learning", description: "New skills and knowledge, not repetition" },
  { id: "prestige", name: "Prestige", description: "Recognition, name-brand, status attached to the role" },
  { id: "structure", name: "Structure", description: "Clear expectations, defined process, less ambiguity" },
  { id: "ambiguity", name: "Ambiguity / building something", description: "Undefined problems, figuring it out as I go" },
  { id: "helping-people", name: "Helping people directly", description: "Seeing the impact of my work on individuals" },
  { id: "big-picture", name: "Big-picture impact", description: "Working on something at scale, even if impersonal" },
  { id: "data-ideas", name: "Working with data or ideas", description: "Analysis, research, abstract problem solving" },
  { id: "hands-on", name: "Working with my hands", description: "Making, building, physical or tangible output" },
  { id: "recognition", name: "Recognition", description: "My contributions are seen and credited" },
  { id: "work-life-separation", name: "Work-life separation", description: "Clear line between work and personal time" },
  { id: "total-immersion", name: "Total immersion", description: "Comfortable with work being a big part of identity" },
  { id: "location-freedom", name: "Location freedom", description: "Not tied to one city or office" },
  { id: "near-family", name: "Being near family/friends", description: "Physical proximity to people I care about" },
  { id: "competitive", name: "Competitive environment", description: "Energized by being pushed and compared" },
  { id: "collaborative", name: "Collaborative environment", description: "Energized by shared credit and teamwork" },
  { id: "risk-tolerance", name: "Risk tolerance", description: "Comfortable with uncertainty for bigger upside" },
  { id: "low-risk", name: "Low risk", description: "Prefer steady, known outcomes over big swings" },
  { id: "intellectual-challenge", name: "Intellectual challenge", description: "Hard problems that stretch my thinking" },
  { id: "simplicity", name: "Simplicity", description: "Clear, manageable scope without constant complexity" },
];
